# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-EN-FindNumber
version:      1.1
version_from: lib/Lingua/EN/FindNumber.pm
installdirs:  site
requires:
    Lingua::EN::Words2Nums:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
