---
abstract: 'Locate (written) numbers in English text '
author:
  - 'Simon Cozens <simon@cpan.org>'
  - 'Tony Bowden <tmtm@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-EN-FindNumber
requires:
  Exporter: '0'
  Lingua::EN::Words2Nums: '0'
  base: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Lingua-EN-FindNumber
  repository: https://github.com/neilbowers/Lingua-EN-FindNumber.git
version: '1.30'
